# -*- coding: utf-8 -*-
"""Ejercicios de Práctica Programación LP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nBf6TOFQnh8Pcrdsi6eTzVfJjJRJIZ1i
"""

primer_nombre = input("Ingresa tu primer nombre: ")
segundo_nombre = input("ingresa tu segundo nombre: ")
primer_apellido = input("Ingresa tu primer apellido: ")
segundo_apellido = input("Ingresa tu segundo apellido:")

print (f"{primer_nombre}.{primer_apellido}@keyinstitute.edu.sv")

Cuenta_total = int(input("Ingresa el valor de tu cuenta: $ "))
Propina = int(input("Elige el porcentaje de propina que quieres darle a tu mesero: 10%, 20%, 30%  "))
Total = (int(Propina / 100 * Cuenta_total))
print (f"El valor total de tu cuenta es de $ {Cuenta_total + Total}")

contraseña = input("Ingresa una contraseña: ")

mayuscula = False
digito = False
simbolo = False

for letra in contraseña:
    if letra.isupper():
        mayuscula = True
        #print("Contiene mayúscula")
    if letra.isdigit():
        digito = True
        #print ("contiene número")
    if letra in ["!", "?", "%"]:
        simbolo = True

if mayuscula and digito and simbolo and len(contraseña) >= 8:
    print ("Contraseña segura")
else:
    print ("Contraseña no segura")

unidades_consumidas = (int(input("Ingrese el valor de unidades consumidas: ")))

if unidades_consumidas <= 100:
    print ("Sin impuestos")

elif unidades_consumidas >=  101:
    contador = unidades_consumidas - 100
    print (contador)
    contador = contador * 0.5
    print (f" Tiene que pagar ${contador} en impuestos")

else:
    contador = unidades_consumidas - 100
    print (contador)
    contador = contador * 0.7
    print (f" Tiene que pagar ${contador} en impuestos")